eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true