services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ../monitoring/loki/loki-config.yml:/etc/loki/local-config.yml
    command:
      - '-config.file=/etc/loki/local-config.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=0000
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DISCORD_WEBHOOK_URL=${GF_DISCORD_WEBHOOK_URL}
    volumes:
      - ../monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
      - loki

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"