apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
spec:
  selector:
    app: auth-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10010
      targetPort: 10010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: t/ticketping/auth-server:latest
          ports:
            - containerPort: 10010
          env:
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: EUREKA_SERVER
            - name: REDIS_NODE_1
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REDIS_NODE_1
            - name: REDIS_NODE_2
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REDIS_NODE_2
            - name: REDIS_NODE_3
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REDIS_NODE_3
            - name: REDIS_NODE_4
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REDIS_NODE_4
            - name: REDIS_NODE_5
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REDIS_NODE_5
            - name: REDIS_NODE_6
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REDIS_NODE_6
            - name: LOKI_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: LOKI_HOST
            - name: ZIPKIN
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: ZIPKIN
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET_KEY