apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  selector:
    app: eureka-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10010
      targetPort: 10010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: taewon171/auth-server:latest
          ports:
            - containerPort: 10010
          env:
            - name: EUREKA_SERVER
              value: ${EUREKA_SERVER}
            - name: REDIS_NODE_1
              value: ${REDIS_NODE_1}
            - name: REDIS_NODE_2
              value: ${REDIS_NODE_2}
            - name: REDIS_NODE_3
              value: ${REDIS_NODE_3}
            - name: REDIS_NODE_4
              value: ${REDIS_NODE_4}
            - name: REDIS_NODE_5
              value: ${REDIS_NODE_5}
            - name: REDIS_NODE_6
              value: ${REDIS_NODE_6}
            - name: LOKI_HOST
              value: ${LOKI_HOST}
            - name: ZIPKIN
              value: ${ZIPKIN}
            - name: JWT_SECRET_KEY
              value: ${JWT_SECRET_KEY}