apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
spec:
  selector:
    app: gateway-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: taewon171/gateway-server:latest
          ports:
            - containerPort: 10001
          env:
            - name: EUREKA_SERVER
              value: ${EUREKA_SERVER}
            - name: REDIS_NODE_1
              value: ${REDIS_NODE_1}
            - name: REDIS_NODE_2
              value: ${REDIS_NODE_2}
            - name: REDIS_NODE_3
              value: ${REDIS_NODE_3}
            - name: REDIS_NODE_4
              value: ${REDIS_NODE_4}
            - name: REDIS_NODE_5
              value: ${REDIS_NODE_5}
            - name: REDIS_NODE_6
              value: ${REDIS_NODE_6}
            - name: ZIPKIN
              value: ${ZIPKIN}
            - name: FRONTEND_APP_URL
              value: ${FRONTEND_APP_URL}
            - name: USER_TOKEN_SECRET_KEY
              value: ${USER_TOKEN_SECRET_KEY}