apiVersion: v1
kind: Service
metadata:
  name: queue-manage-server-service
spec:
  selector:
    app: queue-manage-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10015
      targetPort: 10015
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-manage-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-manage-server
  template:
    metadata:
      labels:
        app: queue-manage-server
    spec:
      containers:
        - name: queue-manage-server
          image: ticketping/queue-manage-server:latest
          ports:
            - containerPort: 10015
          env:
            - name: EUREKA_SERVER
              value: ${EUREKA_SERVER}
            - name: REDIS_NODE_1
              value: ${REDIS_NODE_1}
            - name: REDIS_NODE_2
              value: ${REDIS_NODE_2}
            - name: REDIS_NODE_3
              value: ${REDIS_NODE_3}
            - name: REDIS_NODE_4
              value: ${REDIS_NODE_4}
            - name: REDIS_NODE_5
              value: ${REDIS_NODE_5}
            - name: REDIS_NODE_6
              value: ${REDIS_NODE_6}
            - name: KAFKA_BROKER_1
              value: ${KAFKA_BROKER_1}
            - name: KAFKA_BROKER_2
              value: ${KAFKA_BROKER_2}
            - name: KAFKA_BROKER_3
              value: ${KAFKA_BROKER_3}
            - name: LOKI_HOST
              value: ${LOKI_HOST}
            - name: ZIPKIN
              value: ${ZIPKIN}
            - name: USER_TOKEN_SECRET_KEY
              value: ${USER_TOKEN_SECRET_KEY}
            - name: WORKING_QUEUE_MAX_SIZE
              value: ${WORKING_QUEUE_MAX_SIZE}
            - name: INITIAL_WORKING_QUEUE_TOKEN_TTL
              value: ${INITIAL_WORKING_QUEUE_TOKEN_TTL}
            - name: EXTENDED_WORKING_QUEUE_TOKEN_TTL
              value: ${EXTENDED_WORKING_QUEUE_TOKEN_TTL}