apiVersion: v1
kind: Service
metadata:
  name: user-server-service
spec:
  selector:
    app: user-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10011
      targetPort: 10011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - name: user-server
          image: ticketping/user-server:latest
          ports:
            - containerPort: 10011
          env:
            - name: EUREKA_SERVER
              value: ${EUREKA_SERVER}
            - name: USER_POSTGRES_URL
              value: ${USER_POSTGRES_URL}
            - name: USER_POSTGRES_USERNAME
              value: ${USER_POSTGRES_USERNAME}
            - name: USER_POSTGRES_PASSWORD
              value: ${USER_POSTGRES_PASSWORD}
            - name: LOKI_HOST
              value: ${LOKI_HOST}
            - name: ZIPKIN
              value: ${ZIPKIN}